import {MapObject} from '../MapObject'
import {
  IFRAME_TYPE, IMG_TYPE, SharedContentType, TEXT_TYPE, VIDEO_TYPE,
} from './SharedContentType'

export type SharedContent = ImgSharedContent | IframeSharedContent | TextSharedContent | VideoSharedContent

export interface BaseSharedContent extends MapObject {
  id: string    //  unique ID (generated by participant id + number)
  type: SharedContentType  //  object type ('img', etc)
  size: [number, number]
  zorder: number  //  unix timestamp when shared or moved to top.
}

export interface ImgSharedContent extends BaseSharedContent {
  type: typeof IMG_TYPE
  url: string
}

export interface IframeSharedContent extends BaseSharedContent {
  type: typeof IFRAME_TYPE
  url: string
}

export interface TextSharedContent extends BaseSharedContent {
  type: typeof TEXT_TYPE
  text: string
}

export interface VideoSharedContent extends BaseSharedContent {
  type: typeof VIDEO_TYPE
  stream: MediaStream | undefined
}
