import {MapObject} from './MapObject'
const MAXIMIZABLE_IMAGE_MIN_WIDTH = 200

export type ContentType = 'img' | 'text' | 'pdf' | 'youtube' | 'iframe' | 'screen' | 'camera' |
  'gdrive' | 'whiteboard' | 'playbackScreen' | 'playbackCamera' |  ''

export interface SharedContentInfoData {
  name: string                    //  name or title of the content.
  ownerName: string               //  name of the initial owner
  color:number[]                  //  color in the left var
  textColor:number[]              //  textColor in the left var
  type: ContentType               //  content type ('img', etc)
  playback?: boolean
}
export const defaultSharedContentInfoData: SharedContentInfoData = {
  name:'', ownerName:'', color:[], textColor:[], type:'text'}

export interface SharedContentId{
  id: string                      //  unique ID (generated by participant id + number)
}
export interface SharedContentInfo extends SharedContentInfoData, SharedContentId{
}
export function isEqualSharedContentInfo(a:SharedContentInfo, b:SharedContentInfo){
  return a.name === b.name && a.ownerName === b.ownerName
    && a.color.toString() === b.color.toString() && a.textColor.toString() === b.textColor.toString()
}
export function extractSharedContentInfo(c: SharedContentInfo){
  const rv:SharedContentInfo = {id:c.id, name: c.name, ownerName: c.ownerName,
    color:c.color, textColor: c.textColor, type: c.type}

  return rv
}

export type ZoneType = 'open' | 'close'

export interface SharedContentDataToSend extends SharedContentInfoData {
  zorder: number                  //  unix timestamp when shared or moved to top.
  url: string                     //  url or text to share
  size: [number, number]          //  current size of the content
  originalSize: [number, number]  //  original size of the content or [0, 0]
  pinned: boolean                //  pinned (not resizable or resizable)
  noFrame?: boolean               //  no (invisible) frame
  opacity?: number                //  opacity
  zone?: ZoneType                 //  is this a audio zone is the zone closed or open?
}

export interface SharedContentData extends SharedContentDataToSend {
  playback?: boolean                  //  is playback or normal content
  zIndex?: number                     //  zIndex for display
  overlapZones: ISharedContent[]      //  other zones overlap this
  surroundingZones: ISharedContent[]  //  surrounded zones
}

export interface ISharedContent extends MapObject, SharedContentData, SharedContentId {
}
export interface ISharedContentToSend extends MapObject, SharedContentDataToSend, SharedContentId {
}
export interface ISharedContentToSave extends MapObject, SharedContentDataToSend{
}

//  Callers (sendContentUpdateRequest, Recorder.start()) pass in the same live content objects
//  that ContentStore.all/sorted (and thus RndContent's rendering) also hold onto -- e.g.
//  zIndex is recomputed by ContentStore's own reactive autorun, not stored durably, so deleting
//  it in place here would corrupt the currently-displayed content the moment it's next sent,
//  silently dropping it to z-index:auto (stacks behind anything else that still has one, like a
//  wallpaper image) until some unrelated store change happens to trigger a fresh recompute.
//  Strip the transport-irrelevant fields from a copy instead.
export function contentsToSend(them: ISharedContent[]) {
  return them.map(content => {
    const c = {...content} as any
    delete c.playback
    delete c.zIndex
    delete c.zones
    return c
  }) as ISharedContentToSend[]
}
export function receiveToContents(them: ISharedContentToSend[]) {
  for(const content of them){
    const c = content as ISharedContent
    c.overlapZones = []
    c.surroundingZones = []
  }
  return them as ISharedContent[]
}
//  Same reasoning as contentsToSend() above -- downloadItems() (ShareMenu.tsx) passes
//  contentStore.all directly, so mutating in place would delete id/zIndex/etc. from the
//  currently-displayed content just from exporting the room. Strip from a copy instead.
export function contentsToSave(them: ISharedContent[]) {
  return them.map(content => {
    const c = {...content} as any
    delete c.playback
    delete c.zIndex
    delete c.zones
    delete c.id
    return c
  }) as ISharedContentToSave[]
}
let loadToContentConut = 1
export function loadToContents(them: ISharedContentToSend[]) {
  for(const c of them){
    if (!c.id){
      c.id = "LD" + loadToContentConut
      loadToContentConut ++
    }
  }
  return receiveToContents(them)
}

export const TIME_RESOLUTION_IN_MS = 100
export const TEN_YEAR = 1000 * 60 * 60 * 24 * 365 * 10 / TIME_RESOLUTION_IN_MS

//  Exhaustiveness helper: if a new ContentType is added without updating one of
//  the switches below, TypeScript errors here instead of silently falling through.
function assertNeverContentType(type: never): never {
  throw new Error(`Unhandled ContentType: ${type}`)
}

//  Does content use keyinput during editing or not.
export function doseContentEditingUseKeyinput(c: ISharedContent): boolean {
  switch (c.type) {
    case 'text': case 'pdf':
      return true
    case 'img': case 'youtube': case 'iframe': case 'screen': case 'camera':
    case 'gdrive': case 'whiteboard': case 'playbackScreen': case 'playbackCamera': case '':
      return false
    default:
      return assertNeverContentType(c.type)
  }
}
//  can this type of content be a wall paper or not
export function canContentBeAWallpaper(c?: ISharedContent): boolean {
  if (!c) return false
  switch (c.type) {
    case 'camera': case 'screen':
      return false
    case 'img': case 'text': case 'pdf': case 'youtube': case 'iframe':
    case 'gdrive': case 'whiteboard': case 'playbackScreen': case 'playbackCamera': case '':
      return true
    default:
      return assertNeverContentType(c.type)
  }
}
//  editable or not
export function isContentEditable(c?: ISharedContent): boolean {
  if (!c) return false
  switch (c.type) {
    case 'text': case 'iframe': case 'pdf': case 'whiteboard': case 'gdrive': case 'youtube':
      return true
    case 'img': case 'screen': case 'camera': case 'playbackScreen': case 'playbackCamera': case '':
      return false
    default:
      return assertNeverContentType(c.type)
  }
}
//  maximizable or not
export function isContentMaximizable(c?: ISharedContent): boolean {
  if (!c) return false
  switch (c.type) {
    case 'iframe': case 'pdf': case 'whiteboard': case 'gdrive': case 'youtube':
    case 'screen': case 'camera':
      return true
    case 'img': case 'text':
      return c.size[0] > MAXIMIZABLE_IMAGE_MIN_WIDTH
    case 'playbackScreen': case 'playbackCamera': case '':
      return false
    default:
      return assertNeverContentType(c.type)
  }
}
export function isContentRequireLogin(c?: ISharedContent): boolean {
  if (!c) return false
  switch (c.type) {
    case 'gdrive':
      return true
    case 'img': case 'text': case 'pdf': case 'youtube': case 'iframe': case 'screen': case 'camera':
    case 'whiteboard': case 'playbackScreen': case 'playbackCamera': case '':
      return false
    default:
      return assertNeverContentType(c.type)
  }
}
//  wallpaper or not
export function isContentWallpaper(c?: ISharedContent) {
  return c && c.zorder <= TEN_YEAR
}
export const CONTENT_OUT_OF_RANGE_VALUE = 1024*1024
export function isContentOutOfRange(c?: ISharedContent) {
  return !c || c.pose.position[0] === CONTENT_OUT_OF_RANGE_VALUE
}
export function isContentRtc(c?: SharedContentInfoData): boolean {
  if (!c) return false
  switch (c.type) {
    case 'camera': case 'screen':
      return true
    case 'img': case 'text': case 'pdf': case 'youtube': case 'iframe':
    case 'gdrive': case 'whiteboard': case 'playbackScreen': case 'playbackCamera': case '':
      return false
    default:
      return assertNeverContentType(c.type)
  }
}

export interface WallpaperStore {
  room: string
  contents: SharedContentData[]
}

export interface TextMessage {
  message: string, //  text to display
  name: string, //  The name of whom create this text
  color?:number[]        //  background color
  textColor?:number[]    //  textColor
  pid: string,  //  The pid of whom create this text
  time: number, //  Timestamp when this message created.
}
export interface TextMessages {
  messages: TextMessage[]
  scroll: [number, number]
}

export function compTextMessage(t1: TextMessage, t2: TextMessage) {
  return t1.time - t2.time
}
